import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar";
import { SiteFooter } from "@/components/marketing/SiteFooter";

export const metadata: Metadata = {
  title: "Terms of Service - CV2Hire",
  description: "The terms that govern your use of CV2Hire.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />

      <main className="main-section py-16 flex-1">
        <div className="max-w-3xl w-full mx-auto flex flex-col gap-8">
          <div>
            <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
            <p className="text-light-400 mt-2 text-sm">Last updated: January 2026</p>
          </div>

          <p className="text-light-100 leading-relaxed">
            These terms govern your access to and use of CV2Hire. By creating an account or
            uploading a CV, you agree to them.
          </p>

          <section className="flex flex-col gap-3">
            <h2>1. Using the Service</h2>
            <p>
              CV2Hire provides AI-generated CV analysis and voice mock interviews for personal
              career preparation. You may use the service only for lawful purposes and must not
              upload content you don&apos;t have the right to share, including someone else&apos;s
              personal information.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2>2. Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials
              and for all activity under your account. Notify us immediately if you suspect
              unauthorized access.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2>3. AI-Generated Feedback</h2>
            <p>
              CV scores, interview feedback, and recommendations are generated by AI models and
              are provided for guidance only. They are not a guarantee of interview or job
              outcomes, and you remain responsible for decisions made using this feedback.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2>4. Subscriptions &amp; Billing</h2>
            <p>
              Paid plans are billed on a recurring monthly basis until cancelled. You can cancel
              at any time from your account settings; access continues until the end of the
              current billing period. Fees are non-refundable except where required by law.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2>5. Acceptable Use</h2>
            <p>
              You agree not to reverse engineer the platform, attempt to extract training data
              from the underlying AI models, overload the service through automated requests, or
              use it to generate content intended to deceive an employer (for example, submitting
              AI-fabricated work history as fact).
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2>6. Termination</h2>
            <p>
              We may suspend or terminate accounts that violate these terms. You may close your
              account at any time, after which your CV, interview, and feedback data will be
              deleted in line with our{" "}
              <a href="/privacy" className="text-primary-200 hover:underline">
                Privacy Policy
              </a>
              .
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2>7. Disclaimer &amp; Liability</h2>
            <p>
              The service is provided &ldquo;as is&rdquo; without warranties of any kind. To the
              extent permitted by law, CV2Hire is not liable for indirect or consequential damages
              arising from your use of the platform.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2>8. Contact</h2>
            <p>
              Questions about these terms can be sent to{" "}
              <a href="mailto:support@cv2hire.app" className="text-primary-200 hover:underline">
                support@cv2hire.app
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
